import { TagGroupDefinition, DropdownMap } from '../types';

export const DROPDOWNS: DropdownMap = {
  'EXIF:MeteringMode': {
    '0': 'Unknown',
    '1': 'Average',
    '2': 'Center-weighted average',
    '3': 'Spot',
    '4': 'Multi-spot',
    '5': 'Multi-segment',
    '6': 'Partial',
    '255': 'Other',
  },
  'EXIF:ExposureProgram': {
    '0': 'Not defined',
    '1': 'Manual',
    '2': 'Normal program',
    '3': 'Aperture priority',
    '4': 'Shutter priority',
    '5': 'Creative program',
    '6': 'Action program',
    '7': 'Portrait mode',
    '8': 'Landscape mode',
  },
  'EXIF:WhiteBalance': {
    '0': 'Auto',
    '1': 'Manual',
  },
  'EXIF:LightSource': {
    '0': 'Unknown',
    '1': 'Daylight',
    '2': 'Fluorescent',
    '3': 'Tungsten (incandescent)',
    '4': 'Flash',
    '9': 'Fine weather',
    '10': 'Cloudy weather',
    '11': 'Shade',
  },
  'EXIF:Flash': {
    '0': 'No Flash',
    '1': 'Flash Fired',
    '5': 'Fired, Return not detected',
    '7': 'Fired, Return detected',
    '9': 'Fired, Compulsory',
    '13': 'Fired, Compulsory, Return not detected',
    '15': 'Fired, Compulsory, Return detected',
    '16': 'Off, Compulsory',
    '24': 'Off, Auto',
    '25': 'Fired, Auto',
    '29': 'Fired, Auto, Return not detected',
    '31': 'Fired, Auto, Return detected',
    '32': 'No flash function',
    '65': 'Fired, Red-eye reduction',
    '69': 'Fired, Red-eye reduction, Return not detected',
    '71': 'Fired, Red-eye reduction, Return detected',
    '73': 'Fired, Compulsory, Red-eye reduction',
    '77': 'Fired, Compulsory, Red-eye reduction, Return not detected',
    '79': 'Fired, Compulsory, Red-eye reduction, Return detected',
    '89': 'Fired, Auto, Red-eye reduction',
    '93': 'Fired, Auto, Red-eye reduction, Return not detected',
    '95': 'Fired, Auto, Red-eye reduction, Return detected',
  },
};

export const GROUP_DEFINITIONS: Record<string, TagGroupDefinition> = {
  'General & Descriptions': {
    title: 'General & Descriptions',
    icon: 'description',
    tags: [
      'XMP:Title',
      'XMP:Subject',
      'XMP:Rating',
      'IPTC:Keywords',
      'EXIF:UserComment',
      'EXIF:Artist',
      'EXIF:Copyright',
      'EXIF:ImageUniqueID',
      'EXIF:Software',
    ],
  },
  'Photography & Exposure': {
    title: 'Photography & Exposure',
    icon: 'camera',
    tags: [
      'EXIF:DateTimeOriginal',
      'EXIF:ExposureProgram',
      'EXIF:ISO',
      'EXIF:ExposureTime',
      'EXIF:FNumber',
      'EXIF:ExposureBiasValue',
      'EXIF:FocalLength',
      'EXIF:MaxApertureValue',
      'EXIF:MeteringMode',
      'EXIF:SubjectDistance',
      'EXIF:Flash',
      'EXIF:FlashEnergy',
      'EXIF:FocalLengthIn35mmFormat',
      'EXIF:Contrast',
      'EXIF:BrightnessValue',
      'EXIF:Saturation',
      'EXIF:Sharpness',
      'EXIF:WhiteBalance',
      'EXIF:LightSource',
      'EXIF:DigitalZoomRatio',
      'EXIF:ExifVersion',
    ],
  },
  'Camera & Lens Info': {
    title: 'Camera & Lens Info',
    icon: 'sliders',
    tags: [
      'EXIF:Make',
      'EXIF:Model',
      'EXIF:SerialNumber',
      'EXIF:LensMake',
      'EXIF:LensModel',
      'EXIF:FlashMake',
      'EXIF:FlashModel',
    ],
  },
  'Positioning (GPS)': {
    title: 'Positioning (GPS)',
    icon: 'pin',
    tags: [
      'EXIF:GoogleMapsCoordinates',
      'EXIF:GPSAltitude',
    ],
  },
  'Image Engineering (Read-Only Specs)': {
    title: 'Image Engineering (Read-Only Specs)',
    icon: 'image',
    tags: [
      'EXIF:ExifImageWidth',
      'EXIF:ExifImageHeight',
      'EXIF:XResolution',
      'EXIF:YResolution',
      'EXIF:BitsPerSample',
      'EXIF:Compression',
      'EXIF:ColorSpace',
      'EXIF:CompressedBitsPerPixel',
      'EXIF:PhotometricInterpretation',
    ],
  },
};
